version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/staticfiles
    expose:
      - "8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend.dev
    command: npm run dev
    volumes:
      - ./frontend/:/app
      - /frontend/node_modules/
    expose:
      - "3000"
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
